import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/widgets/custom_button.dart';
import '../../../../core/widgets/glass_container.dart';
import '../../../auth/viewmodels/auth_viewmodel.dart';
import '../../../../core/services/academic_provider.dart';

class AttendanceDashboardScreen extends StatefulWidget {
  const AttendanceDashboardScreen({super.key});

  @override
  State<AttendanceDashboardScreen> createState() => _AttendanceDashboardScreenState();
}

class _AttendanceDashboardScreenState extends State<AttendanceDashboardScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _onMarkGps(AcademicProvider provider, String uid) {
    // Simulate user standing inside school gates (25.5942, 85.1377)
    final bool success = provider.markAttendanceViaGps(
      lat: 25.5942,
      lon: 85.1377,
      studentUid: uid,
    );

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(success ? 'Attendance Marked!' : 'Location Failure'),
        content: Text(
          success
              ? 'GPS verified device is inside school gates. Present marked successfully.'
              : 'Verified location is outside school radius boundaries.',
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('OK')),
        ],
      ),
    );
  }

  void _onScanQrMock(AcademicProvider provider, String uid) {
    if (provider.activeQrCode == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No active QR code generated by the teacher.')),
      );
      return;
    }

    final bool success = provider.markAttendanceViaQr(provider.activeQrCode!, uid);

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(success ? 'Scan Successful!' : 'QR Code Expired'),
        content: Text(
          success
              ? 'Attendance code verified. Present logged.'
              : 'This QR code is either invalid or expired.',
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('OK')),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = Provider.of<AuthViewModel>(context).userProfile;
    final acadProvider = Provider.of<AcademicProvider>(context);
    final bool isDark = Theme.of(context).brightness == Brightness.dark;

    if (user == null) {
      return const Center(child: CircularProgressIndicator());
    }

    final bool isStaff = user.role == 'Teacher' || user.role == 'Admin' || user.role == 'Super Admin';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Smart Attendance System'),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(text: 'QR Attendance', icon: Icon(Icons.qr_code)),
            Tab(text: 'GPS Location Check', icon: Icon(Icons.location_on)),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // QR CODE ATTENDANCE
          SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              children: [
                if (isStaff) ...[
                  // Teacher interface
                  GlassContainer(
                    child: Column(
                      children: [
                        const Text('Teacher QR Console', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        const SizedBox(height: 12),
                        const Text(
                          'Generate a time-expiring QR code. Students scanning this code inside their portal will be logged present.',
                          textAlign: TextAlign.center,
                          style: TextStyle(color: Colors.grey, fontSize: 12),
                        ),
                        const SizedBox(height: 24),
                        if (acadProvider.activeQrCode != null) ...[
                          Container(
                            width: 180,
                            height: 180,
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(16),
                            ),
                            child: const Center(
                              child: Icon(Icons.qr_code, size: 120, color: Colors.black),
                            ),
                          ),
                          const SizedBox(height: 16),
                          Text(
                            'Expires in: ${acadProvider.qrCountdownSeconds} seconds',
                            style: const TextStyle(fontWeight: FontWeight.bold, color: AppColors.secondaryOrange),
                          ),
                        ] else ...[
                          CustomButton(
                            text: 'Generate QR Code',
                            onPressed: () => acadProvider.generateQrCode(),
                          ),
                        ]
                      ],
                    ),
                  ),
                ] else ...[
                  // Student interface
                  GlassContainer(
                    child: Column(
                      children: [
                        const Text('Scan Attendance QR', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        const SizedBox(height: 12),
                        const Text(
                          'Scan the active code displayed on the teacher board to confirm your class presence.',
                          textAlign: TextAlign.center,
                          style: TextStyle(color: Colors.grey, fontSize: 12),
                        ),
                        const SizedBox(height: 32),
                        Container(
                          width: 220,
                          height: 220,
                          decoration: BoxDecoration(
                            border: Border.all(color: AppColors.primaryBlue, width: 2),
                            borderRadius: BorderRadius.circular(24),
                            color: isDark ? AppColors.darkSurface : Colors.grey[500],
                          ),
                          child: const Center(
                            child: Icon(Icons.camera_alt_outlined, color: Colors.white, size: 48),
                          ),
                        ),
                        const SizedBox(height: 32),
                        CustomButton(
                          text: 'Simulate Scanning QR',
                          onPressed: () => _onScanQrMock(acadProvider, user.uid),
                        ),
                      ],
                    ),
                  ),
                ]
              ],
            ),
          ),
          
          // GPS BOUNDARY CHECK
          SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: GlassContainer(
              child: Column(
                children: [
                  const Text('GPS Boundary Verification', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                  const SizedBox(height: 12),
                  const Text(
                    'Verification verifies that the device GPS coordinates match within 80 meters of the school center coordinates (Patna Campus).',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.grey, fontSize: 12),
                  ),
                  const SizedBox(height: 32),
                  const CircleAvatar(
                    radius: 48,
                    backgroundColor: Color(0xFFEAFFF4),
                    child: Icon(Icons.gps_fixed, color: AppColors.accentGreen, size: 36),
                  ),
                  const SizedBox(height: 32),
                  CustomButton(
                    text: 'Verify Coordinates & Mark',
                    onPressed: () => _onMarkGps(acadProvider, user.uid),
                  ),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }
}
