import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/widgets/custom_button.dart';
import '../../../../core/widgets/glass_container.dart';
import '../../../auth/viewmodels/auth_viewmodel.dart';
import '../../../../core/services/academic_provider.dart';

class AttendanceDashboardScreen extends StatefulWidget {
  const AttendanceDashboardScreen({super.key});

  @override
  State<AttendanceDashboardScreen> createState() => _AttendanceDashboardScreenState();
}

class _AttendanceDashboardScreenState extends State<AttendanceDashboardScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;
  bool _showClassWiseAttendancePage = false;
  String? _selectedClassForAttendance;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  String _formatSeconds(int totalSeconds) {
    final int hours = totalSeconds ~/ 3600;
    final int minutes = (totalSeconds % 3600) ~/ 60;
    final int seconds = totalSeconds % 60;
    return '${hours.toString().padLeft(2, '0')}h ${minutes.toString().padLeft(2, '0')}m ${seconds.toString().padLeft(2, '0')}s';
  }

  void _onMarkGps(AcademicProvider provider, String uid) {
    final bool success = provider.markAttendanceViaGps(
      lat: 25.5942,
      lon: 85.1377,
      studentUid: uid,
    );

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(success ? 'Attendance Marked!' : 'Location Failure'),
        content: Text(
          success
              ? 'GPS verified device is inside school gates. Present marked successfully.'
              : 'Verified location is outside school radius boundaries.',
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('OK')),
        ],
      ),
    );
  }

  void _onScanQrMock(AcademicProvider provider, String uid) {
    if (provider.activeQrCode == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No active QR code generated by the teacher.')),
      );
      return;
    }
    setState(() {
      _showClassWiseAttendancePage = true;
      _selectedClassForAttendance = null;
    });
  }

  Widget _buildClassWiseAttendanceView(BuildContext context, AcademicProvider acadProvider) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final List<String> classes = [
      'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 
      'Class 7', 'Class 8', 'Class 9', 'Class 10', 'Class 11', 'Class 12'
    ];

    if (_selectedClassForAttendance != null) {
      final List<String> mockRoster = [
        'Aman Agarwal', 'Ravi Shankar', 'Priya Kumari', 'Sneha Patel', 'Animesh Roy'
      ];
      return GlassContainer(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () {
                    setState(() {
                      _selectedClassForAttendance = null;
                    });
                  },
                ),
                Text(
                  'Roster: $_selectedClassForAttendance',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                ),
              ],
            ),
            const SizedBox(height: 12),
            const Text(
              'Select your name below to mark yourself Present:',
              style: TextStyle(fontSize: 12, color: Colors.grey),
            ),
            const SizedBox(height: 16),
            Column(
              children: mockRoster.map((name) {
                return Card(
                  margin: const EdgeInsets.symmetric(vertical: 6),
                  color: isDark ? AppColors.darkSurface : Colors.white,
                  child: ListTile(
                    title: Text(name, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                    trailing: const Icon(Icons.check_circle_outline, color: Colors.green),
                    onTap: () {
                      showDialog(
                        context: context,
                        builder: (context) => AlertDialog(
                          title: const Text('Confirm Attendance'),
                          content: Text('Are you sure you want to log presence for $name in $_selectedClassForAttendance?'),
                          actions: [
                            TextButton(
                              onPressed: () => Navigator.pop(context),
                              child: const Text('Cancel'),
                            ),
                            ElevatedButton(
                              style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
                              onPressed: () {
                                Navigator.pop(context);
                                setState(() {
                                  _showClassWiseAttendancePage = false;
                                });
                                ScaffoldMessenger.of(context).showSnackBar(
                                  SnackBar(
                                    content: Text('Success! Attendance marked for $name! 🎉'),
                                    backgroundColor: Colors.green,
                                  ),
                                );
                              },
                              child: const Text('Confirm', style: TextStyle(color: Colors.white)),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                );
              }).toList(),
            ),
          ],
        ),
      );
    }

    return GlassContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Agarwal Knowledge Hub',
                style: TextStyle(fontWeight: FontWeight.w900, fontSize: 16, color: Colors.blue),
              ),
              IconButton(
                icon: const Icon(Icons.close),
                onPressed: () {
                  setState(() {
                    _showClassWiseAttendancePage = false;
                  });
                },
              ),
            ],
          ),
          const SizedBox(height: 6),
          const Text(
            'Select your Class to proceed with self-attendance:',
            style: TextStyle(fontSize: 12, color: Colors.grey),
          ),
          const SizedBox(height: 16),
          GridView.builder(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: classes.length,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              crossAxisSpacing: 8,
              mainAxisSpacing: 8,
              childAspectRatio: 2.2,
            ),
            itemBuilder: (context, index) {
              final className = classes[index];
              return ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: isDark ? AppColors.darkSurface : Colors.grey[200],
                  foregroundColor: isDark ? Colors.white : Colors.black87,
                  elevation: 0,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  padding: EdgeInsets.zero,
                ),
                onPressed: () {
                  setState(() {
                    _selectedClassForAttendance = className;
                  });
                },
                child: Text(className, style: const TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
              );
            },
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = Provider.of<AuthViewModel>(context).userProfile;
    final acadProvider = Provider.of<AcademicProvider>(context);
    final bool isDark = Theme.of(context).brightness == Brightness.dark;

    if (user == null) {
      return const Center(child: CircularProgressIndicator());
    }

    final bool isStaff = user.role == 'Teacher' || user.role == 'Admin' || user.role == 'Super Admin';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Smart Attendance System'),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(text: 'QR Attendance', icon: Icon(Icons.qr_code)),
            Tab(text: 'GPS Location Check', icon: Icon(Icons.location_on)),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              children: [
                if (isStaff) ...[
                  GlassContainer(
                    child: Column(
                      children: [
                        const Text('Teacher QR Console', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        const SizedBox(height: 12),
                        Text(
                          'Active Class Scope: ${acadProvider.qrClassScope}',
                          style: const TextStyle(fontWeight: FontWeight.bold, color: AppColors.primaryBlue, fontSize: 13),
                        ),
                        const SizedBox(height: 8),
                        const Text(
                          'Generate a 24-hour expiring QR code. Students scanning this code inside their portal will see class selection.',
                          textAlign: TextAlign.center,
                          style: TextStyle(color: Colors.grey, fontSize: 11),
                        ),
                        const SizedBox(height: 24),
                        if (acadProvider.activeQrCode != null) ...[
                          Container(
                            width: 180,
                            height: 180,
                            padding: const EdgeInsets.all(8),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(16),
                            ),
                            child: Center(
                              child: acadProvider.customQrUrl != null
                                  ? Image.network(acadProvider.customQrUrl!)
                                  : Image.network(
                                      'https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${acadProvider.activeQrCode}',
                                      loadingBuilder: (context, child, loadingProgress) {
                                        if (loadingProgress == null) return child;
                                        return const CircularProgressIndicator();
                                      },
                                    ),
                            ),
                          ),
                          const SizedBox(height: 16),
                          Text(
                            'Rotates in: ${_formatSeconds(acadProvider.qrCountdownSeconds)}',
                            style: const TextStyle(fontWeight: FontWeight.bold, color: AppColors.secondaryOrange),
                          ),
                        ] else ...[
                          CustomButton(
                            text: 'Generate 24h QR Code',
                            onPressed: () => acadProvider.generateQrCode(),
                          ),
                        ]
                      ],
                    ),
                  ),
                ] else ...[
                  if (_showClassWiseAttendancePage)
                    _buildClassWiseAttendanceView(context, acadProvider)
                  else
                    GlassContainer(
                      child: Column(
                        children: [
                          const Text('Scan Attendance QR', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                          const SizedBox(height: 12),
                          const Text(
                            'Scan the active code displayed on the teacher board to confirm your class presence.',
                            textAlign: TextAlign.center,
                            style: TextStyle(color: Colors.grey, fontSize: 12),
                            ),
                            const SizedBox(height: 32),
                            Container(
                              width: 220,
                              height: 220,
                              decoration: BoxDecoration(
                                border: Border.all(color: AppColors.primaryBlue, width: 2),
                                borderRadius: BorderRadius.circular(24),
                                color: isDark ? AppColors.darkSurface : Colors.grey[500],
                              ),
                              child: const Center(
                                child: Icon(Icons.camera_alt_outlined, color: Colors.white, size: 48),
                              ),
                            ),
                            const SizedBox(height: 32),
                            CustomButton(
                              text: 'Simulate Scanning QR',
                              onPressed: () => _onScanQrMock(acadProvider, user.uid),
                            ),
                          ],
                        ),
                      ),
                  ]
                ],
              ),
            ),
          
          // GPS BOUNDARY CHECK
          SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: GlassContainer(
              child: Column(
                children: [
                  const Text('GPS Boundary Verification', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                  const SizedBox(height: 12),
                  const Text(
                    'Verification verifies that the device GPS coordinates match within 80 meters of the school center coordinates (Patna Campus).',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.grey, fontSize: 12),
                  ),
                  const SizedBox(height: 32),
                  const CircleAvatar(
                    radius: 48,
                    backgroundColor: Color(0xFFEAFFF4),
                    child: Icon(Icons.gps_fixed, color: AppColors.accentGreen, size: 36),
                  ),
                  const SizedBox(height: 32),
                  CustomButton(
                    text: 'Verify Coordinates & Mark',
                    onPressed: () => _onMarkGps(acadProvider, user.uid),
                  ),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }
}
